### ISSUE TITLE
docker pull command in documentation

### ISSUE THREAD

**Issue by cmhosale** [hipstas/kaldi-pop-up-archive#1]
I got an error about a "latest" tag being missing when running docker pull without options, but was able to get what I needed with the command "docker pull -a hipstas/kaldi-pop-up-archive". The documentation could be updated, or the version updated to work with just the pull command? It might have been the way I have docker set up, I don't know.

**Comment by privatezero** [comment]
Had the same problem on Ubuntu 16.04 - @cmhosale's tip to add `-a` seems to have fixed it on my end as well!

**Comment by stevemclaugh** [comment]
Thanks, @cmhosale and @privatezero — good catch. I'm not using the 'latest' tag, which 'docker pull' is expecting, because I had to build the image locally. For automated builds, Docker Hub will apply 'latest' to the most recent version ... but keeping up with that convention by hand is a pain. I used the label 'v1' here, but forgot to include it in the readme.

```
docker pull hipstas/kaldi-pop-up-archive:v1
```

Thanks again!
